server {
    listen 80;
    server_name localhost;

    # Tắt Access Log hoàn toàn
    access_log off;

    # Hoặc định hướng Access Log và Error Log về /dev/null
    # access_log /dev/null;
    error_log /dev/null crit;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }
}
